# Generated by Django 3.0.4 on 2020-09-05 07:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('app_description', models.TextField()),
                ('app_link', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 9, 5, 7, 40, 54, 111213, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_at', models.DateTimeField(null=True)),
                ('app_id', models.ForeignKey(db_column='app_id', on_delete=django.db.models.deletion.CASCADE, to='main.App')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
