# Generated by Django 3.0.4 on 2020-09-05 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscriber',
        ),
        migrations.AlterField(
            model_name='app',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 11, 24, 49, 160001, tzinfo=utc)),
        ),
    ]
