# Generated by Django 3.0.4 on 2020-09-05 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200905_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='default_visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 13, 18, 36, 358740, tzinfo=utc)),
        ),
    ]
